title: Luis Costa
email: luispcosta18@gmail.com
description:
baseurl: ""
url: "https://luispcosta.github.io"
github_username:  luispcosta
theme: minima
show_excerpts: true

header_pages:
 - about.md
 - projects.md